version: "3"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
  flyway:
    image: flyway/flyway:latest
    command: -locations="filesystem:/flyway/sql" -connectRetries=60 -url=jdbc:postgresql://postgres:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME} -user=${POSTGRES_DB_USER} -password=${POSTGRES_DB_PASSWORD} clean baseline migrate

    volumes:
      - ./src/postgres/migrations:/flyway/sql
      - ./conf:/flyway/conf
    depends_on:
      - postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
