version: "3"
services:
  neo4j:
    container_name: Neo4j-test
    image: neo4j:4.2.3
    volumes:
      - ./data:/data/neo4j
      - ./plugins:/plugins/neo4j
      - ./import:/import/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_pagecache_size=283m
      - NEO4J_dbms_memory_heap_max__size=512m
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
    networks: ["Neo4j-test"]
    restart: unless-stopped
networks: { Neo4j-test: {} }
# use docker volume to persist data outside of a container.
volumes:
  Neo4j-test:
